[package]
name = "tripfuse"
version = "0.1.0"
edition = "2024"
authors=["oOp<ossama.abboud95@gmai.com>"]
repository="https://github.com/oOp995/tripfuse"
documentation = "https://docs.rs/tripfuse"
homepage="https://github.com/oOp995/tripfuse"
description="A one-time use container for sensitive values"
license = "MIT OR Apache-2.0"
readme="README.md"
categories = ["cryptography", "security", "authentication", "rust-patterns"]

keywords = [
    "one-time",
    "fuse",
    "security",
    "secrets",
    "otp",
    "consumable",
    "single-use",
    "token",
    "authenticator",
    "once"
]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
